[package]
name = "core"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
lazy_static = "1.4.0"
once_cell = "1.17.1"
regex = "1.7.0"
rust-i18n = "1.1.4"
serde = "1.0.152"
serde_derive = "1.0.152"
toml = "0.5.10"
