[swahili]
# language keywords
number_ = "nambari"
bool_ = "bulin"
string_ = "mlolongo"
true_ = "kweli"
false_ = "ongo"
if_ = "kama"
is_ = "ni"
# builtin functions
print = "andika"
printf = "andika_umbizo"
sprint = "mlolongo_andika"
sprintf = "mlolongo_andika_umbizo"
println = "andika_laini"
len = "urefu"
